Декоративные элементы главной страницы
htmlacademy-adaptive/1643657-mishka-22 pull request #11
Opened 2021-05-02 16:19 UTC by KateMoro

2021-05-04 12:14 UTC, wrgraff requested changes
Все вроде хорошо, пора к ПП приступать. Там где-то заголовки не того размера, где-то пространства между буквами поправить надо. В общем-то, правок мало по нему. Можно уже подтянуть вполне.

Из больших багов вот тут меню надо поправить на планшете, оно странно тянется:
<img width="695" alt="изображение" src="https://user-images.githubusercontent.com/37917037/117001300-d7eeac80-acea-11eb-9d4a-7d83ef019bb7.png">

Мне одно только не нравится в проекте. Как-то так недосмотрел я что ли в прошлых частях, но у тебя то резина, то фикс. Где удобно резину делать, там резина. Где удобно фикс, там фикс.
Особенно в хэдере. Надо или хэдер переверстать на фикс, или весь сайт резинить. Что выбираешь?

2021-05-04 12:14 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    content: url("../../img/flag.svg");
Путь неправильный.
Надо пусть ставить от конечной папки. Он у тебя может сработать, если на сервере уже некуда выходить вверх будет после первого выхода. Но на реальном сервере велика вероятность, что будет куда выйти. И картинка не покажется.

2021-05-04 12:14 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +  left: 50%;
Модалка должна всплывать по центру экрана, она не должна быть привязана к какому-то одному месту на странице.
Надо менять и положение, и тип позиционирования.

2021-05-04 12:14 UTC, wrgraff commented on source/sass/blocks/product-categories.scss
> +}
Этот блок в целом должен быть над серым фоном. А у тебя по краям он белый.
<img width="1558" alt="изображение" src="https://user-images.githubusercontent.com/37917037/117001651-459ad880-aceb-11eb-861a-9493a861e2df.png">

2021-05-04 13:00 UTC, KateMoro commented on source/sass/blocks/contacts.scss
> +    content: url("../../img/flag.svg");
Да. Это косяк =( Знаю же, что один выход из папки нужен

2021-05-04 13:00 UTC, KateMoro commented on source/sass/blocks/modal.scss
> +  left: 50%;
Немного самодеятельности))

2021-05-05 13:45 UTC, wrgraff requested changes

2021-05-05 13:45 UTC, wrgraff commented on source/index.html
> +      <div class="intro container">
Легко тут не отделаешься.
Фоны то тянуться должны:
![изображение](https://user-images.githubusercontent.com/37917037/117147044-882ce580-adbd-11eb-8d92-6d3ace56b1c1.png)

Думаем дальше =)

2021-05-05 13:45 UTC, wrgraff commented on source/index.html
> +      <section class="product-categories page-main__center page-main__center--shiftup">
Зеленые кнопки должны тоже тянуться на мобильном.
При чем, кнопки — да, а текст с иконками внутри должен быть центрирован.

И еще смещение при наведении на мобильном не нужно, надо отключить.

2021-05-05 13:45 UTC, wrgraff commented on source/index.html
> +      <section class="product-categories page-main__center page-main__center--shiftup">
Зачем тебе, кстати, 2 контейнера?
И `container`, и `page-main__center`.

2021-05-05 13:45 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +  transform: translate(-50%, -50%);
Смещение влево лучше оставить отступом: оно более производительное и жрет меньше ресурсов

2021-05-05 13:45 UTC, wrgraff commented on source/sass/blocks/page-main.scss
> +}
Как-то не очень здорово, что это для такого общего элемента. Ведь поднять нужно кнопки в довольно частом случае.
Да еще и нюанс есть с тем, что для переполнения это не самый оптимальный способ.

Скорее всего, тебе все равно придется оборачивать элементы, чтобы сделать и центрирование, и тянущийся фон. Можно там и это учесть, и волнистую границу туда перенести.

2021-05-05 13:45 UTC, wrgraff commented on source/sass/blocks/about.scss
> +  }
То есть, поленилась сделать более универсальный код для иконок?
Или не получилось?

2021-05-05 13:45 UTC, wrgraff commented on source/sass/blocks/category-link.scss
> +  }
При наведении у тебя получается дергание небольшое:
https://user-images.githubusercontent.com/37917037/117150782-21113000-adc1-11eb-8635-29fe131d2869.mov

Придумай как этот эффект реализовать, не меняя размеры элементов. А то с блочной моделью когда мудришь, всегда очень легко словить баги с подергиваниями и прочими подпрыгиваниями

2021-05-08 10:33 UTC, wrgraff requested changes

2021-05-08 10:33 UTC, wrgraff commented on source/sass/blocks/product-categories.scss
> +  transition: 0.5s ease-in;
Указывай свойство, которое делаешь плавным. Иначе ты анимируешь вообще все и можно нарваться на какую-нибудь странность

2021-05-08 10:33 UTC, wrgraff commented on source/sass/blocks/product-categories.scss
> +      top: -5px;
Сдвигай элементы через `transform`. Особенно если плавно двигаешь, трансформации для этого лучше оптимизированы, чем изменение параметров для `position`.

2021-05-08 10:33 UTC, wrgraff commented on source/sass/blocks/product-categories.scss
> +      height: 105%;
Ну и что это за высота такая в итоге получается? =)
Изначально сделай элемент больше. Добавь ему больше нижний отступ, чтобы был запас. И расположи его так, чтобы нижняя часть закрывалась. И просто двигай при наведении элемент вверх.

Старайся избегать изменения геометрии самого элемента при взаимодействии с ним. Изменение размеров может влиять на соседние элементы, и даже если оно компенсируется как-то, то не факт, что на каждом шаге анимации это не вызывает перерисовку интерфейса.

2021-05-08 12:04 UTC, merged