Адаптивная сетка для главной страницы
htmlacademy-adaptive/1643657-mishka-22 pull request #8
Opened 2021-04-17 20:31 UTC by KateMoro

2021-04-18 18:17 UTC, wrgraff commented on source/sass/blocks/about.scss
> +    margin-left: 175px;
Еще бы верхний отступ сбросить но помешало

2021-04-18 18:23 UTC, wrgraff commented on source/sass/blocks/about.scss
> +    margin-left: 175px;
Вот тут есть ощущение, что что-то пошло не так, потому что 2 ранве колонки так и остались двумя колонками, но вдруг вместо `1fr` приобрели размер.
Стоитт подумать как сохранить относительные величины и не переписывать шаблон сетки

2021-04-18 21:34 UTC, wrgraff requested changes
Ну хорошая сетка вышла, я считаю.
Но надо еще подтянуть местами гибкость. И подумать все-таки про фикс хотя бы сначала

2021-04-18 21:34 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    grid-row: 1/2;
Нет ли смысла перейти на grid-area, если уж приходится задавать и колонку и ряд?
Хотя, я не до конца понимаю зачем они тебе вообще (ну, кроме карты)

2021-04-18 21:34 UTC, wrgraff commented on source/sass/blocks/container.scss
> +  }
Стоит подумать все-таки о фиксированной верстке.
Раньше так и рекомендовали. Сперва фикс научиться делать, а затем если есть силы и время переделать на резину, то сделать и это

2021-04-18 21:34 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    grid-row: 2/3;
Тут тоже стоит бы задуматься, а не проще ли через именованные области перемешивать их

2021-04-18 21:34 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +  box-shadow: 0 5px 10px rgba(0, 1, 1, 0.25);
Как думаешь, что за цвет такой внутри rgb: `0, 1, 1`? =)
Можно ли кое-чем пренебречь тут?

2021-04-18 21:34 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +    grid-template-columns: 1fr 1fr 1fr;
Так у тебя идеально ровные колонки получатся. Да.
А теперь посмотри на макет повнимательнее...

2021-04-18 21:34 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +    grid-template-columns: 1fr auto;
Какой-то ну очень непредсказуемый грид...
Может, сделать вторую колонку 175 точек, чтобы кнопку в ней растянуло ровно на нужное значение? И отступы подбирать не придется.

А еще стоит добавлять gap'ы, даже если их не видно на самом макете. Так будет надежнее сетка, так как в ней уже будет продумано отсутствие прилипания:
![изображение](https://user-images.githubusercontent.com/37917037/115161497-a8169680-a0a6-11eb-9740-bb275b61540a.png)

2021-04-18 21:34 UTC, wrgraff commented on source/sass/blocks/size-item.scss
> +  width: 80px;
А что, если вдруг понадобится что-то нестандартное написать там?

2021-04-19 22:34 UTC, KateMoro commented on source/sass/blocks/modal.scss
> +  box-shadow: 0 5px 10px rgba(0, 1, 1, 0.25);
Нет идей 😀

2021-04-21 08:42 UTC, wrgraff approved these changes

2021-04-21 08:42 UTC, wrgraff commented on source/sass/blocks/size-item.scss
> +  padding: 18px 30px;
Еще можно было сделать паддинги меньше, а ширину задать через `min-width`, чтобы в случае чего было куда расти

2021-04-21 08:42 UTC, merged